# Generated by Django 5.0.3 on 2024-05-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='email',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
