# Generated by Django 5.0.3 on 2024-05-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatsession_email_chatsession_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatsessionmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chatsessionmessage',
            name='name',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats1', to='chat.chatuser'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats2', to='chat.chatuser'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.chatuser'),
        ),
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatuser'),
        ),
        migrations.AlterField(
            model_name='chattext',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chattexts', to='chat.chatuser'),
        ),
    ]
