# Generated by Django 5.0.3 on 2024-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatuser_remove_chatsessionmessage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
