# Generated by Django 5.0.3 on 2024-04-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miners',
            name='use',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='use',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='use',
        ),
    ]
