# Generated by Django 5.0.3 on 2024-04-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='user',
        ),
    ]
