# Generated by Django 3.2.25 on 2024-06-15 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20240615_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='align',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level1',
            field=models.ManyToManyField(related_name='_auctions_user_level1_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='level2',
            field=models.ManyToManyField(related_name='_auctions_user_level2_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='level3',
            field=models.ManyToManyField(related_name='_auctions_user_level3_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profitlist',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.plans'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='id',
            field=models.CharField(default='4f5ee6f6-5', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
