# Generated by Django 5.0.3 on 2024-04-09 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_user_wallet_userid_remove_plans_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plans',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={},
        ),
        migrations.AddField(
            model_name='addamountreq',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.currencies'),
        ),
        migrations.AddField(
            model_name='addamountreq',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminverifybank',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminverifymelli',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='askamountreq',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.currencies'),
        ),
        migrations.AddField(
            model_name='askamountreq',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencies',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitlist',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.currencies'),
        ),
        migrations.AddField(
            model_name='profitlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjects',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.currencies'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verify',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.currencies'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addamountreq',
            name='curid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addamountreq',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='askamountreq',
            name='curid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='askamountreq',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bazdid',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='planid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profitlist',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='subid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='act',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='curid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Miners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='miner')),
                ('des', models.TextField(max_length=10000)),
                ('rate', models.FloatField(null=True)),
                ('period', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.currencies')),
            ],
        ),
    ]
