# Generated by Django 5.0.3 on 2024-04-09 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_currencies_options_alter_plans_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='curid',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='userid',
        ),
        migrations.AddField(
            model_name='plans',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.currencies'),
        ),
    ]
