# Generated by Django 5.0.3 on 2024-04-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_wallet_curid_remove_wallet_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miners',
            old_name='cur',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='cur',
        ),
    ]
