# Generated by Django 5.0.3 on 2024-04-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_addamountreq_use_askamountreq_use_bid_use_job_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='user',
        ),
    ]
