# Generated by Django 5.0.3 on 2024-04-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_plans_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miners',
            name='use',
        ),
        migrations.RemoveField(
            model_name='miners',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='use',
        ),
    ]
