# Generated by Django 5.0.3 on 2024-04-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_cur_miners_currency_remove_plans_cur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addamountreq',
            name='curid',
        ),
        migrations.RemoveField(
            model_name='addamountreq',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='adminverifybank',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='adminverifymelli',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='askamountreq',
            name='curid',
        ),
        migrations.RemoveField(
            model_name='askamountreq',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='job',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='profitlist',
            name='curid',
        ),
        migrations.RemoveField(
            model_name='profitlist',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='curid',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='verify',
            name='userid',
        ),
        migrations.AddField(
            model_name='bid',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.plans'),
        ),
        migrations.AddField(
            model_name='profitlist',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.plans'),
        ),
    ]
