# Generated by Django 5.0.3 on 2024-04-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_addamountreq_curid_remove_addamountreq_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='planid',
        ),
        migrations.RemoveField(
            model_name='profitlist',
            name='planid',
        ),
    ]
