# Generated by Django 5.0.3 on 2024-04-11 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bid_planid_remove_profitlist_planid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedMiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('miner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.miners')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
