# Generated by Django 5.0.3 on 2024-04-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_adminverifybank_use_adminverifymelli_use_verify_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
