# Generated by Django 5.0.3 on 2024-04-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rentedminer_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedminer',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
