# Generated by Django 5.0.3 on 2024-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rentedminer_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedminer',
            name='paid',
            field=models.FloatField(default=0, null=True),
        ),
    ]
