# Generated by Django 5.0.3 on 2024-04-20 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_rentedminer_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('pic', models.ImageField(upload_to='blog')),
                ('place', models.CharField(default='normal', max_length=100)),
            ],
        ),
    ]
