# Generated by Django 3.2.25 on 2024-06-26 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20240626_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
