# Generated by Django 5.0.3 on 2024-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_elan'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.BooleanField(default=False),
        ),
    ]
