# Generated by Django 5.0.3 on 2024-05-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_post_app_post_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='miner')),
                ('des', models.TextField(max_length=10000)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
