# Generated by Django 5.0.3 on 2024-05-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=100)),
                ('last_name', models.ImageField(upload_to='products')),
                ('address', models.TextField(max_length=10000)),
                ('postal_code', models.TextField(max_length=10)),
            ],
        ),
    ]
