# Generated by Django 5.0.3 on 2024-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
