# Generated by Django 5.0.3 on 2024-05-19 13:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_pages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
