# Generated by Django 5.0.3 on 2024-05-19 13:43

import ckeditor5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_pages_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='text',
            field=ckeditor5.fields.RichTextField(),
        ),
    ]
