# Generated by Django 5.0.3 on 2024-05-20 12:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
